### ISSUE TITLE
Upload name is undefined in alert. 

### ISSUE THREAD

**Issue by insomniacmonkey** [nilsjohnson/gif-it#22]
While a video is converting if a user hits the share button the title of the gif is not defined. 
Steps to reproduce:

1. login
2. click upload
3. upload a file
4. while the upload is in progress click "share" 
5. See popup with issue. 

Note: it also says "or remove it" and I don't think that is possible. 

![undefined](https://user-images.githubusercontent.com/391495/96067504-7f93b280-0e5f-11eb-8ac3-e7b9154af8f3.png)

**Comment by nilsjohnson** [comment]
Fixed it, thanks!
