### ISSUE TITLE
Description icon is broken

### ISSUE THREAD

**Issue by insomniacmonkey** [nilsjohnson/gif-it#23]
The icon on the "please enter description" page is broken. 
Steps to repo:
1. login
2. upload a file
3. once file is uploaded see the "please enter a description" page
![brokeMyHeart](https://user-images.githubusercontent.com/391495/96067681-edd87500-0e5f-11eb-9646-b73dfb29459c.png)

**Comment by nilsjohnson** [comment]
[See issue #26 ](https://github.com/nilsjohnson/gif-it/issues/26)
