### ISSUE TITLE
Share model icon is broken

### ISSUE THREAD

**Issue by insomniacmonkey** [nilsjohnson/gif-it#24]
The share modal icon is broken on the share page. 
Steps to repo: 
1. login
2. upload a video
3. once upload is finished select "share" button
4. see issue on share page. 

![morebrokenhearts](https://user-images.githubusercontent.com/391495/96067881-4e67b200-0e60-11eb-95ac-9c1731ebb2ec.png)

**Comment by nilsjohnson** [comment]
[See issue #26](https://github.com/nilsjohnson/gif-it/issues/26)
