### ISSUE TITLE
User is unable to cancel an upload in progress

### ISSUE THREAD

**Issue by insomniacmonkey** [nilsjohnson/gif-it#27]
The cancel button does not appear to be working at all 😭 

https://gif-it.io/87n3c8vm.gif

Steps to repo:
1. login
2. upload a file
3. while that file is uploading click the "cancel" button
4. see that nothing happens. (issue)

**Comment by nilsjohnson** [comment]
Hi Chanse!
I addressed this issue. I moved the button inside the upload's container and it's wired to stop the upload, during upload. To cancel the upload at a different point, user's can click on the trash can on the upload's file bar.
